//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schmidt.TechnicalPlan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class TechnicalPlan : global::System.Configuration.ApplicationSettingsBase {
        
        private static TechnicalPlan defaultInstance = ((TechnicalPlan)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TechnicalPlan())));
        
        public static TechnicalPlan Default {
            get {
                return defaultInstance;
            }
        }
    }
}
